CREATE TYPE "board_access_role" AS ENUM (
  'owner',
  'member',
  'observer',
  'guest'
);

CREATE TYPE "task_status" AS ENUM (
  'new',
  'todo',
  'in_progress',
  'in_review',
  'completed'
);

CREATE TABLE "boards" (
  "board_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "icon_slug" varchar,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_id" varchar,
  "name" varchar NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp
);

CREATE TABLE "users_boards" (
  "user_id" bigint,
  "board_id" bigint,
  "role" board_access_role
);

CREATE TABLE "tags" (
  "tag_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "board_id" bigint,
  "label" varchar NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp
);

CREATE TABLE "tasks" (
  "task_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "status" task_status DEFAULT 'new',
  "thumbnail_url" varchar,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp,
  "board_id" bigint
);

CREATE TABLE "tasks_tags" (
  "task_id" bigint,
  "tag_id" bigint
);

ALTER TABLE "users_boards" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "users_boards" ADD FOREIGN KEY ("board_id") REFERENCES "boards" ("board_id");

ALTER TABLE "tasks" ADD FOREIGN KEY ("board_id") REFERENCES "boards" ("board_id");

ALTER TABLE "tags" ADD FOREIGN KEY ("board_id") REFERENCES "boards" ("board_id");

ALTER TABLE "tasks_tags" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("task_id");

ALTER TABLE "tasks_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id");
